# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e44420caafb7d4e82945977340744be399bf3d5a82c4ff539d55797a33e057c16664b0d431b5e48beb121c752178a3eb601ad653d50338ae0ded855012009837

test:
  secret_key_base: 0e1dae7ab2516871500f8d5886538af4580669bb14c398e180ea092bc7e5a1ae7237e1141ce925f6f3348c0038011a4f427430ca6613ad9902388383f6934632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
